all: stack_management thread_cleanup thread_creation

stack_management:
	gcc stack_management.c -lpthread -o stack_management

thread_cleanup:
	gcc thread_cleanup.c -lpthread -o thread_cleanup

thread_creation:
	gcc thread_creation.c -lpthread -o thread_creation


clean:
	rm -rf stack_management thread_cleanup thread_creation

