all: fork_example1 fork_example2

fork_example1:
	gcc fork_example1.c -o fork_example1

fork_example2:
	gcc fork_example2.c -o fork_example2


clean: 
	@echo clean
	@rm -rf fork_example1 fork_example2
